//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace DW_YBBX.WebReference1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JwsServiceImplPortBinding", Namespace="http://service.communication.service.dareway.com/")]
    public partial class JwsServiceImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginByYybmOperationCompleted;
        
        private System.Threading.SendOrPostCallback invokeOperationCompleted;
        
        private System.Threading.SendOrPostCallback invokeSiOperationCompleted;
        
        private System.Threading.SendOrPostCallback invokeCottonOperationCompleted;
        
        private System.Threading.SendOrPostCallback dipInvokeOperationCompleted;
        
        private System.Threading.SendOrPostCallback pipInvokeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JwsServiceImplService() {
            this.Url = global::DW_YBBX.Properties.Settings.Default.众阳医保报销接口_WebReference1_JwsServiceImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event loginByYybmCompletedEventHandler loginByYybmCompleted;
        
        /// <remarks/>
        public event invokeCompletedEventHandler invokeCompleted;
        
        /// <remarks/>
        public event invokeSiCompletedEventHandler invokeSiCompleted;
        
        /// <remarks/>
        public event invokeCottonCompletedEventHandler invokeCottonCompleted;
        
        /// <remarks/>
        public event dipInvokeCompletedEventHandler dipInvokeCompleted;
        
        /// <remarks/>
        public event pipInvokeCompletedEventHandler pipInvokeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.communication.service.dareway.com/", ResponseNamespace="http://service.communication.service.dareway.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string login(string arg0, string arg1) {
            object[] results = this.Invoke("login", new object[] {
                        arg0,
                        arg1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string arg0, string arg1) {
            this.loginAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void loginAsync(string arg0, string arg1, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        arg0,
                        arg1}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.communication.service.dareway.com/", ResponseNamespace="http://service.communication.service.dareway.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("loginResult1")]
        public string loginByYybm(string arg0, string arg1, string arg2) {
            object[] results = this.Invoke("loginByYybm", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginByYybmAsync(string arg0, string arg1, string arg2) {
            this.loginByYybmAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void loginByYybmAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.loginByYybmOperationCompleted == null)) {
                this.loginByYybmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginByYybmOperationCompleted);
            }
            this.InvokeAsync("loginByYybm", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.loginByYybmOperationCompleted, userState);
        }
        
        private void OnloginByYybmOperationCompleted(object arg) {
            if ((this.loginByYybmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginByYybmCompleted(this, new loginByYybmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.communication.service.dareway.com/", ResponseNamespace="http://service.communication.service.dareway.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultContent")]
        public string invoke(string arg0, string arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("invoke", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invokeAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.invokeAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void invokeAsync(string arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.invokeOperationCompleted == null)) {
                this.invokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvokeOperationCompleted);
            }
            this.InvokeAsync("invoke", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.invokeOperationCompleted, userState);
        }
        
        private void OninvokeOperationCompleted(object arg) {
            if ((this.invokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invokeCompleted(this, new invokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.communication.service.dareway.com/", ResponseNamespace="http://service.communication.service.dareway.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultContent")]
        public string invokeSi(string arg0, string arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("invokeSi", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invokeSiAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.invokeSiAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void invokeSiAsync(string arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.invokeSiOperationCompleted == null)) {
                this.invokeSiOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvokeSiOperationCompleted);
            }
            this.InvokeAsync("invokeSi", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.invokeSiOperationCompleted, userState);
        }
        
        private void OninvokeSiOperationCompleted(object arg) {
            if ((this.invokeSiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invokeSiCompleted(this, new invokeSiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.communication.service.dareway.com/", ResponseNamespace="http://service.communication.service.dareway.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultContent")]
        public string invokeCotton(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            object[] results = this.Invoke("invokeCotton", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invokeCottonAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            this.invokeCottonAsync(arg0, arg1, arg2, arg3, arg4, arg5, null);
        }
        
        /// <remarks/>
        public void invokeCottonAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, object userState) {
            if ((this.invokeCottonOperationCompleted == null)) {
                this.invokeCottonOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvokeCottonOperationCompleted);
            }
            this.InvokeAsync("invokeCotton", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5}, this.invokeCottonOperationCompleted, userState);
        }
        
        private void OninvokeCottonOperationCompleted(object arg) {
            if ((this.invokeCottonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invokeCottonCompleted(this, new invokeCottonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.communication.service.dareway.com/", ResponseNamespace="http://service.communication.service.dareway.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultContent")]
        public string dipInvoke(string arg0, string arg1, string arg2) {
            object[] results = this.Invoke("dipInvoke", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dipInvokeAsync(string arg0, string arg1, string arg2) {
            this.dipInvokeAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void dipInvokeAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.dipInvokeOperationCompleted == null)) {
                this.dipInvokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndipInvokeOperationCompleted);
            }
            this.InvokeAsync("dipInvoke", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.dipInvokeOperationCompleted, userState);
        }
        
        private void OndipInvokeOperationCompleted(object arg) {
            if ((this.dipInvokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dipInvokeCompleted(this, new dipInvokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.communication.service.dareway.com/", ResponseNamespace="http://service.communication.service.dareway.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("resultContent")]
        public string pipInvoke(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            object[] results = this.Invoke("pipInvoke", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pipInvokeAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            this.pipInvokeAsync(arg0, arg1, arg2, arg3, arg4, arg5, null);
        }
        
        /// <remarks/>
        public void pipInvokeAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, object userState) {
            if ((this.pipInvokeOperationCompleted == null)) {
                this.pipInvokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpipInvokeOperationCompleted);
            }
            this.InvokeAsync("pipInvoke", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5}, this.pipInvokeOperationCompleted, userState);
        }
        
        private void OnpipInvokeOperationCompleted(object arg) {
            if ((this.pipInvokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pipInvokeCompleted(this, new pipInvokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void loginByYybmCompletedEventHandler(object sender, loginByYybmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginByYybmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginByYybmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void invokeCompletedEventHandler(object sender, invokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void invokeSiCompletedEventHandler(object sender, invokeSiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invokeSiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invokeSiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void invokeCottonCompletedEventHandler(object sender, invokeCottonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invokeCottonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invokeCottonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void dipInvokeCompletedEventHandler(object sender, dipInvokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dipInvokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dipInvokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void pipInvokeCompletedEventHandler(object sender, pipInvokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pipInvokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pipInvokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591